// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM7NhMpOSEpAWm4EJAtWonIhhuidOp12E',
    appId: '1:808335310742:web:8a19b5eff594af405427b7',
    messagingSenderId: '808335310742',
    projectId: 'asmaa-flutter-chat-app',
    authDomain: 'asmaa-flutter-chat-app.firebaseapp.com',
    storageBucket: 'asmaa-flutter-chat-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyqD4pjnZ0JP9IRqR-He8j4uO6aYrBVPw',
    appId: '1:808335310742:android:94bd7ceeb8c076aa5427b7',
    messagingSenderId: '808335310742',
    projectId: 'asmaa-flutter-chat-app',
    storageBucket: 'asmaa-flutter-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZq_NsU7vRs8JlEemLOu6xEavmcNTR9H8',
    appId: '1:808335310742:ios:c17a60b9c2bb5f3f5427b7',
    messagingSenderId: '808335310742',
    projectId: 'asmaa-flutter-chat-app',
    storageBucket: 'asmaa-flutter-chat-app.appspot.com',
    iosClientId: '808335310742-rqd1a41beef4oetfkejkjbve92ol42em.apps.googleusercontent.com',
    iosBundleId: 'com.example.courseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZq_NsU7vRs8JlEemLOu6xEavmcNTR9H8',
    appId: '1:808335310742:ios:2d831ac879def2dc5427b7',
    messagingSenderId: '808335310742',
    projectId: 'asmaa-flutter-chat-app',
    storageBucket: 'asmaa-flutter-chat-app.appspot.com',
    iosClientId: '808335310742-s5mpktckpjcall4cvfrj45nj61j1crcl.apps.googleusercontent.com',
    iosBundleId: 'com.example.courseApp.RunnerTests',
  );
}
